import { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: {
    default: 'Learning Next',
    template: '%s | Craig',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className='h-screen'
    >
      <body>
        <header style={{ backgroundColor: 'lightblue', padding: '1rem' }}>
          Header
        </header>
        {children}
        <footer className='w-full h-12 bg-gray-900'>Footer</footer>
      </body>
    </html>
  );
}
